name = "xmit-mcp"
main = "src/server.ts"
compatibility_date = "2026-01-28"
compatibility_flags = ["nodejs_compat"]

[vars]
TRANSMIT_API_BASE = "https://api.xmit.sh"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "56c42a41c69a4025a9039b25a5baefde"

[[routes]]
pattern = "mcp.xmit.sh/*"
zone_name = "xmit.sh"
